import Head from 'next/head';
import { useState } from 'react';
import { DONATION_IN_CENTS, MAX_DONATION_IN_CENTS } from '../config';

export default function Home() {
  const [error, setError] = useState(null);
  const [quantity, setQuantity] = useState(1);
  const [name, setName] = useState('');
  const [message, setMessage] = useState('');

  const presets = [1, 3, 5];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex'>
        <div>
          <h1>Buy me a beer</h1>
          {presets.map((preset) => {
            return (
              <button key={preset} onClick={() => setQuantity(preset)}>
                {preset}
              </button>
            );
          })}
          <input
            type='number'
            onChange={(e) => setQuantity(parseFloat(e.target.value))}
            value={quantity}
            min={1}
            max={MAX_DONATION_IN_CENTS / DONATION_IN_CENTS}
          />

          <button>Donate ${quantity * (DONATION_IN_CENTS / 100)}</button>
        </div>
      </main>
    </div>
  );
}
